### ISSUE TITLE
Create a readme file

### ISSUE THREAD

**Issue by ahmedwalid05** [AmarProGamer/Discord-Bot-Program#1]
Create a readme file for the project using [Markdown](https://www.makeareadme.com/)
Include a screenshot and a list of features 
Here are some good examples of a good readme
- [Virtual Trucker Rich Presence](https://github.com/VirtualTruckerRPC/Virtual-Trucker-Rich-Presence)
- [teamotes](https://github.com/lostdesign/teamotes)
- [foco](https://github.com/akashnimare/foco)

**Comment by AmarMassoud** [comment]
Issue resolved.
